on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "18"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      # Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Install js-yaml
      - name: Install js-yaml
        run: npm install js-yaml

      # Extract version from pubspec.yaml
      - name: Extract version from pubspec.yaml
        id: extract_version
        run: node get-version.js

      # Clean Cache
      - name: Clean Cache
        run: flutter clean

      # Get Packages
      - name: Get Packages
        run: flutter pub get

      # Build Windows App
      - name: Build Windows App
        run: flutter build windows

      # Set up Inno Setup
      - name: Set up Inno Setup
        run: |
          choco install innosetup
        shell: powershell

      # Run Inno Setup to create installer
      - name: Create Installer
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" path\to\your\script.iss
        shell: powershell

      # Upload Installer as Artifact
      - name: Upload Installer
        uses: actions/upload-artifact@v3
        with:
          name: installer
          path: path\to\output\setup.exe

      # Build APK
      - name: Build APK
        run: flutter build apk --release --split-per-abi

      # Build Web
      - name: Build Web
        run: flutter build web

      # Adjust Base HREF
      - name: Adjust Base HREF
        run: sed -i 's|<base href="/">|<base href="/flixstar/">|' build/web/index.html

      # Deploy To GitHub Pages
      - name: Deploy To GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir:
            ./build/web

            # Push to GitHub Releases
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "path/to/output/setup.exe"
          tag: ${{ steps.extract_version.outputs.version }}
          token: ${{ secrets.TOKEN }}

      # Push to Releases
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: ${{ steps.extract_version.outputs.version }}
          token: ${{ secrets.TOKEN }}
